More integration work & switch to 0event logger.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -17,6 +17,7 @@ Usage: $0 [OPTION]... [VAR=VALUE]...
 
   Build options:
     --build-dir=DIR         place build files in directory [build]
+    --log-level=LEVEL       maximum compile-time log level [verbose]
     --generator=GENERATOR   CMake generator to use (see cmake --help)
     --with-cxx=PATH         path to a C++ compiler executable
 
@@ -29,7 +30,6 @@ Usage: $0 [OPTION]... [VAR=VALUE]...
 
   Required packages in non-standard locations:
     --with-libcppa=PATH     path to libcppa install root
-    --with-ze=PATH          path to 0vent install root
     --with-boost=PATH       path to Boost install root
 
   Optional packages in non-standard locations:
@@ -57,12 +57,42 @@ append_cache_entry () {
     CMakeCacheEntries="$CMakeCacheEntries -D $1:$2=$3"
 }
 
+levelize() {
+  case "$1" in
+    quiet)
+      echo 0
+      ;;
+    error)
+      echo 1
+      ;;
+    warn)
+      echo 2
+      ;;
+    info)
+      echo 3
+      ;;
+    verbose)
+      echo 4
+      ;;
+    debug)
+      echo 5
+      ;;
+    trace)
+      echo 5
+      ;;
+    *)
+      echo "invalid log level specification, use:"
+      echo "  quiet|error|warn|info|verbose|debug|trace"
+      exit 1;
+  esac
+}
+
 # Set defaults
 builddir=build
 CMakeCacheEntries=""
-append_cache_entry CMAKE_INSTALL_PREFIX  PATH   /usr/local/vast
-append_cache_entry ENABLE_DEBUG          BOOL   false
-append_cache_entry ENABLE_PERFTOOLS_HEAP BOOL   false
+append_cache_entry CMAKE_INSTALL_PREFIX   PATH      /usr/local/vast
+append_cache_entry ENABLE_DEBUG           BOOL      false
+append_cache_entry ENABLE_PERFTOOLS_HEAP  BOOL      false
 append_cache_entry CPACK_SOURCE_IGNORE_FILES STRING
 
 # parse arguments
@@ -83,20 +113,20 @@ while [ $# -ne 0 ]; do
         --generator=*)
             CMakeGenerator="$optarg"
             ;;
+        --log-level=*)
+            append_cache_entry VAST_LOG_LEVEL INTEGER $(levelize $optarg)
+            ;;
         --prefix=*)
-            append_cache_entry CMAKE_INSTALL_PREFIX PATH   $optarg
+            append_cache_entry CMAKE_INSTALL_PREFIX PATH $optarg
             ;;
         --enable-debug)
-            append_cache_entry ENABLE_DEBUG BOOL   true
+            append_cache_entry ENABLE_DEBUG BOOL true
             ;;
         --with-cxx=*)
             append_cache_entry CMAKE_CXX_COMPILER FILEPATH $optarg
             ;;
         --enable-perftools-heap)
-            append_cache_entry ENABLE_PERFTOOLS_HEAP BOOL   true
-            ;;
-        --with-ze=*)
-            append_cache_entry 0event_ROOT_DIR PATH $optarg
+            append_cache_entry ENABLE_PERFTOOLS_HEAP BOOL true
             ;;
         --with-libcppa=*)
             append_cache_entry LIBCPPA_ROOT_DIR PATH $optarg
