Tweak the configure script.
Now config.status contains escaped arguments so that it can be invoked
with paths containing spaces as well.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2,15 +2,20 @@
 # Convenience wrapper for easily viewing/setting options that
 # the project's CMake scripts will recognize
 
-command="$0 $*"
-sourcedir="$(cd "$(dirname "$0")" && pwd)"
 type cmake > /dev/null 2>&1 || {
-    echo "\
+  echo "\
 This package requires CMake, please install it first, then you may
 use this configure script to access CMake equivalent functionality.\
 " >&2;
-    exit 1;
+  exit 1;
 }
+
+# Save some values for later before parsing the command line.
+if [ -n "$*" ]; then
+  args=$(printf " \"%s\"" $*)
+fi
+command="$0$args"
+sourcedir="$(cd "$(dirname "$0")" && pwd)"
 
 usage="\
 Usage: $0 [OPTION]... [VAR=VALUE]...
@@ -38,17 +43,7 @@ Usage: $0 [OPTION]... [VAR=VALUE]...
     --with-perftools=PATH   path to gperftools install root
     --with-pcap=PATH        path to libpcap install root
     --with-doxygen=PATH     path to Doxygen install root
-
-  Packaging options (for developers):
-    --binary-package        toggle special logic for binary packaging
-    --ignore-dirs=PATHS     paths to ignore when creating source package
-                            (semicolon delimited and quoted when multiple)
-    --pkg-name-prefix=NAME  use the given name as the package prefix instead
-                            of the default CMake project name
-    --osx-sysroot=PATH      path to the OS X SDK to compile against
-    --osx-min-version=VER   minimum OS X version (the deployment target)
 "
-
 
 # Function to append a CMake cache entry definition to the
 # CMakeCacheEntries variable
@@ -99,100 +94,83 @@ append_cache_entry CMAKE_INSTALL_PREFIX   PATH      /usr/local/vast
 append_cache_entry VAST_LOG_LEVEL         INTEGER   $(levelize debug)
 append_cache_entry ENABLE_DEBUG           BOOL      false
 append_cache_entry ENABLE_PERFTOOLS_HEAP  BOOL      false
-append_cache_entry CPACK_SOURCE_IGNORE_FILES STRING
 
-# parse arguments
+# Parse command line arguments.
 while [ $# -ne 0 ]; do
-    case "$1" in
-        -*=*)
-          optarg="$(echo "$1" | sed 's/[-_a-zA-Z0-9]*=//')"
-          ;;
-        *)
-          optarg=
-          ;;
-    esac
-    case "$1" in
-        --help|-h)
-            echo "${usage}" 1>&2
-            exit 1
-            ;;
-        --build-dir=*)
-            builddir="$optarg"
-            ;;
-        --build-type=*)
-            append_cache_entry CMAKE_BUILD_TYPE STRING "$optarg"
-            ;;
-        --generator=*)
-            CMakeGenerator="$optarg"
-            ;;
-        --log-level=*)
-            append_cache_entry VAST_LOG_LEVEL INTEGER $(levelize "$optarg")
-            ;;
-        --prefix=*)
-            append_cache_entry VAST_PREFIX PATH "$optarg"
-            append_cache_entry CMAKE_INSTALL_PREFIX PATH "$optarg"
-            ;;
-        --enable-debug)
-            append_cache_entry VAST_LOG_LEVEL INTEGER $(levelize trace)
-            append_cache_entry ENABLE_DEBUG BOOL true
-            ;;
-        --enable-tcmalloc)
-            append_cache_entry ENABLE_PERFTOOLS_HEAP BOOL true
-            ;;
-        --enable-asan)
-            append_cache_entry ENABLE_ADDRESS_SANITIZER BOOL true
-            ;;
-        --with-caf=*)
-            append_cache_entry CAF_ROOT_DIR PATH "$optarg"
-            ;;
-        --with-boost=*)
-            append_cache_entry BOOST_ROOT PATH "$optarg"
-            ;;
-        --with-doxygen=*)
-            append_cache_entry Doxygen_ROOT_DIR PATH "$optarg"
-            ;;
-        --with-pcap=*)
-            append_cache_entry PCAP_ROOT_DIR PATH "$optarg"
-            ;;
-        --with-editline=*)
-            append_cache_entry EDITLINE_ROOT_DIR PATH "$optarg"
-            ;;
-        --with-perftools=*)
-            append_cache_entry Gperftools_ROOT_DIR PATH "$optarg"
-            ;;
-        --binary-package)
-            append_cache_entry BINARY_PACKAGING_MODE BOOL true
-            ;;
-        --ignore-dirs=*)
-            append_cache_entry CPACK_SOURCE_IGNORE_FILES STRING "$optarg"
-            ;;
-        --pkg-name-prefix=*)
-            append_cache_entry PACKAGE_NAME_PREFIX STRING "$optarg"
-            ;;
-        --osx-sysroot=*)
-            append_cache_entry CMAKE_OSX_SYSROOT PATH "$optarg"
-            ;;
-        --osx-min-version=*)
-            append_cache_entry CMAKE_OSX_DEPLOYMENT_TARGET STRING "$optarg"
-            ;;
-        *)
-            echo "Invalid option '$1'.  Try $0 --help to see available options."
-            exit 1
-            ;;
-    esac
-    shift
+  case "$1" in
+    -*=*)
+      optarg="$(echo "$1" | sed 's/[-_a-zA-Z0-9]*=//')"
+      ;;
+    *)
+      optarg=
+      ;;
+  esac
+  case "$1" in
+    --help|-h)
+      echo "${usage}" 1>&2
+      exit 1
+      ;;
+    --build-dir=*)
+      builddir="$optarg"
+      ;;
+    --build-type=*)
+      append_cache_entry CMAKE_BUILD_TYPE STRING "$optarg"
+      ;;
+    --generator=*)
+      CMakeGenerator="$optarg"
+      ;;
+    --log-level=*)
+      append_cache_entry VAST_LOG_LEVEL INTEGER $(levelize $optarg)
+      ;;
+    --prefix=*)
+      append_cache_entry VAST_PREFIX PATH "$optarg"
+      append_cache_entry CMAKE_INSTALL_PREFIX PATH "$optarg"
+      ;;
+    --enable-debug)
+      append_cache_entry VAST_LOG_LEVEL INTEGER $(levelize trace)
+      append_cache_entry ENABLE_DEBUG BOOL true
+      ;;
+    --enable-tcmalloc)
+      append_cache_entry ENABLE_PERFTOOLS_HEAP BOOL true
+      ;;
+    --enable-asan)
+      append_cache_entry ENABLE_ADDRESS_SANITIZER BOOL true
+      ;;
+    --with-caf=*)
+      append_cache_entry CAF_ROOT_DIR PATH "$optarg"
+      ;;
+    --with-boost=*)
+      append_cache_entry BOOST_ROOT PATH "$optarg"
+      ;;
+    --with-pcap=*)
+      append_cache_entry PCAP_ROOT_DIR PATH "$optarg"
+      ;;
+    --with-editline=*)
+      append_cache_entry EDITLINE_ROOT_DIR PATH "$optarg"
+      ;;
+    --with-perftools=*)
+      append_cache_entry Gperftools_ROOT_DIR PATH "$optarg"
+      ;;
+    --with-doxygen=*)
+      append_cache_entry Doxygen_ROOT_DIR PATH "$optarg"
+      ;;
+    *)
+      echo "Invalid option '$1'.  Try $0 --help to see available options."
+      exit 1
+      ;;
+  esac
+  shift
 done
 
 if [ -d "$builddir" ]; then
-    # If build directory exists, check if it has a CMake cache
-    if [ -f "$builddir/CMakeCache.txt" ]; then
-        # If the CMake cache exists, delete it so that this configuration
-        # is not tainted by a previous one
-        rm -f "$builddir/CMakeCache.txt"
-    fi
+  # If build directory exists, check if it has a CMake cache
+  if [ -f "$builddir/CMakeCache.txt" ]; then
+    # If the CMake cache exists, delete it so that this configuration
+    # is not tainted by a previous one
+    rm -f "$builddir/CMakeCache.txt"
+  fi
 else
-    # Create build directory
-    mkdir -p "$builddir"
+  mkdir -p "$builddir"
 fi
 
 cd "$builddir"
@@ -201,7 +179,7 @@ cd "$builddir"
 # line before passing it to CMake.
 cmake=cmake
 if [ -n "$CMakeGenerator" ]; then
-  cmake="$cmake -G \"$CMakeGenerator\" "
+  cmake="$cmake -G \"$CMakeGenerator\""
 fi
 cmake="$cmake $CMakeCacheEntries \"$sourcedir\""
 eval $cmake
@@ -222,8 +200,7 @@ if [ -n "$CXXFLAGS" ]; then
   printf "CXXFLAGS=%s" $CXXFLAGS >> config.status
   printf ' ' >> config.status
 fi
-printf "$command\n" >> config.status
-
+printf "$command\n" $@ >> config.status
 chmod u+x config.status
 
 makefile="$sourcedir/Makefile"
