Connect to VAST as Compose service
It works when running the neuron independently,
("./vast-cortex-neuron/tests/test service")
but fails when it is executed from Cortex
("Container could not be started")

diff --git a/docker/thehive/vol/vast-cortex-neuron/tests/test b/docker/thehive/vol/vast-cortex-neuron/tests/test
--- a/docker/thehive/vol/vast-cortex-neuron/tests/test
+++ b/docker/thehive/vol/vast-cortex-neuron/tests/test
@@ -4,19 +4,41 @@ set -e
 
 SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" &> /dev/null && pwd)
 EXPECTED_OUTPUT_FILE=$SCRIPT_DIR/output/output.json
+PROJECT_DIRECTORY="--project-directory $SCRIPT_DIR/../../../"
 
-rm -f EXPECTED_OUTPUT_FILE
-
-docker compose -f $SCRIPT_DIR/../../../docker-compose.yaml \
-    run \
-    --entrypoint vast/search.py \
-    --volume $SCRIPT_DIR:/job \
-    --interactive=false \
-    --no-TTY \
-    neuron \
-    /job
-
-if [ ! -f "$EXPECTED_OUTPUT_FILE" ]; then
-    echo "$EXPECTED_OUTPUT_FILE not found"
-    exit 1
+COMPOSE_FILES="-f docker-compose.yaml"
+if [[ "$1" == "service" ]]; then
+  COMPOSE_FILES=" -f ../vast/docker-compose.yaml ${COMPOSE_FILES} -f docker-compose.vast.yaml"
+elif [[ "$1" == "host" ]]; then
+  COMPOSE_FILES=$COMPOSE_FILES
+else
+  echo "Missing argument service|host"
+  exit 1
 fi
+
+# Cleanup before
+rm -f EXPECTED_OUTPUT_FILE
+docker compose $PROJECT_DIRECTORY \
+  $COMPOSE_FILES \
+  down -v
+
+docker compose $PROJECT_DIRECTORY \
+  $COMPOSE_FILES \
+  run \
+  --entrypoint vast/search.py \
+  --volume $SCRIPT_DIR/input/$1.json:/job/input/input.json \
+  --volume $SCRIPT_DIR/output:/job/output \
+  --interactive=false \
+  --no-TTY \
+  --rm \
+  neuron \
+  /job \
+  || true
+
+# Cleanup after
+docker compose $PROJECT_DIRECTORY \
+  $COMPOSE_FILES \
+  down -v
+
+grep -q "\"success\": true" $EXPECTED_OUTPUT_FILE || \
+  (echo "Neuron execution failed" && exit 1)
