Always run last job for checking branch protections

diff --git a/.github/workflows/vast.yaml b/.github/workflows/vast.yaml
--- a/.github/workflows/vast.yaml
+++ b/.github/workflows/vast.yaml
@@ -1065,9 +1065,16 @@ jobs:
       - vast-plugins
       - python
       - python-package
+    if: always()
     runs-on: ubuntu-latest
     name: Pass Branch Protections
     steps:
+      - name: Failure
+        if: contains(join(needs.*.result, ','), 'failure') || contains(join(needs.*.result, ','), 'cancelled')
+        run: |
+          # This check runs after any other job failed.
+          exit 1
       - name: Success
         run: |
-          echo "This check runs after all other jobs are done or skipped"
+          # This check runs after all other jobs are done or skipped
+          exit 0
